# Generated by Django 3.2.6 on 2021-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods'),
        ),
    ]
